

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: 0.0.0.0:8080
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ishtaev73 
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ishtaev73
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: